\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\PassOptionsToPackage{hyphens}{url} % url is loaded by hyperref
\usepackage[unicode=true]{hyperref}
\hypersetup{
            pdftitle={Project 1: Reproducible Research},
            pdfauthor={Paul Ighofose},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Project 1: Reproducible Research}
\author{Paul Ighofose}
\date{2/26/2021}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\NormalTok{opts_chunk}\OperatorTok{$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{echo =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Personal Activity
Monitoring}\label{personal-activity-monitoring}

This data set utilizes personal activity data obtained from an anonymous
individual. Its observations (i.e.~step count) were recorded via five
minute intervals during the months of October and November of 2012. It
is my intention to read and process the data to discover a daily mean
and median step count, its distribution, and the wholesomeness of the
data and its potential affects on any analytically output generated. All
data and views represented within this study are not implications on the
population as a whole, yet is only a fragmented representation of how
personal activity data could, potentially, be utilized to further
understand an individuals daily patterns and possibly its affects on
health.

\subsection{Methods}\label{methods}

Utilizing R, the personal activity monitoring data set was read into the
IDE and processed to provide a data frame consisting of three
columns(i.e.~steps,date, \& interval) with 17,768 observations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{###Installing necessary R packages:}
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages ------------------------------------ tidyverse 1.3.0 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.3     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts --------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{###Reading Data into R:}
\NormalTok{activity <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"Activity Monitoring.csv"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(activity)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      steps            date              interval     
##  Min.   :  0.00   Length:17568       Min.   :   0.0  
##  1st Qu.:  0.00   Class :character   1st Qu.: 588.8  
##  Median :  0.00   Mode  :character   Median :1177.5  
##  Mean   : 37.38                      Mean   :1177.5  
##  3rd Qu.: 12.00                      3rd Qu.:1766.2  
##  Max.   :806.00                      Max.   :2355.0  
##  NA's   :2304
\end{verbatim}

Of those observations, 2,304 or approximately 13.1\% of the steps were
noted as ``Na's'' and indicated a need for removal. An identifier (Id),
was applied to the data set to ensure consistency and correlation
between step,date, and interval observations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Id <-}\StringTok{ }\DecValTok{1}\OperatorTok{:}\DecValTok{17568}
\NormalTok{activity.Id <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(Id, activity)}
\KeywordTok{head}\NormalTok{(activity.Id,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Id steps    date interval
## 1  1    NA 10/1/12        0
## 2  2    NA 10/1/12        5
## 3  3    NA 10/1/12       10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Steps <-}\StringTok{ }\NormalTok{activity.Id }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(Id, steps)}
\NormalTok{interval <-}\StringTok{ }\NormalTok{activity.Id }\OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(Id,interval)}
\NormalTok{dAte <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(activity}\OperatorTok{$}\NormalTok{date, }\StringTok{"%m/%d/%y"}\NormalTok{)}
\NormalTok{id <-}\StringTok{ }\NormalTok{activity.Id}\OperatorTok{$}\NormalTok{Id}
\NormalTok{Data <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Id =}\NormalTok{ id, }\DataTypeTok{steps =}\NormalTok{ activity.Id}\OperatorTok{$}\NormalTok{steps, }\DataTypeTok{date =}\NormalTok{ dAte, }\DataTypeTok{interval =}\NormalTok{ activity.Id}\OperatorTok{$}\NormalTok{interval)}
\NormalTok{Movement <-}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(Data)}
\KeywordTok{tibble}\NormalTok{(Movement)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15,264 x 4
##       Id steps date       interval
##    <int> <int> <date>        <int>
##  1   289     0 2012-10-02        0
##  2   290     0 2012-10-02        5
##  3   291     0 2012-10-02       10
##  4   292     0 2012-10-02       15
##  5   293     0 2012-10-02       20
##  6   294     0 2012-10-02       25
##  7   295     0 2012-10-02       30
##  8   296     0 2012-10-02       35
##  9   297     0 2012-10-02       40
## 10   298     0 2012-10-02       45
## # ... with 15,254 more rows
\end{verbatim}

To further understand the total number of steps taken each day, a loop
was applied to summarize the steps observations diurnally. From the
matrix provided, the date column was subset and integrated with the sum
total step count to provide a more robust data frame. More so, the same
process was replicated to determine, both, the mean and median step
counts per day.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{daily.sum <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(Movement}\OperatorTok{$}\NormalTok{steps,Movement}\OperatorTok{$}\NormalTok{date,sum)}
\KeywordTok{head}\NormalTok{(daily.sum,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2012-10-02 2012-10-03 2012-10-04 
##        126      11352      12116
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{step.sum <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{sum =}\NormalTok{ (daily.sum))}
\NormalTok{Dates <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{c}\NormalTok{(}\StringTok{"2012/10/02"}\NormalTok{, }\StringTok{"2012/10/03"}\NormalTok{,}\StringTok{"2012/10/04"}\NormalTok{,}\StringTok{"2012/10/05"}\NormalTok{,}\StringTok{"2012/10/06"}\NormalTok{,}\StringTok{"2012/10/07"}\NormalTok{,}\StringTok{"2012/10/09"}\NormalTok{,}\StringTok{"2012/10/10"}\NormalTok{,}\StringTok{"2012/10/11"}\NormalTok{,}\StringTok{"2012/10/12"}\NormalTok{,}\StringTok{"2012/10/13"}\NormalTok{,}\StringTok{"2012/10/14"}\NormalTok{,}\StringTok{"2012/10/15"}\NormalTok{,}\StringTok{"2012/10/16"}\NormalTok{,}\StringTok{"2012/10/17"}\NormalTok{,}\StringTok{"2012/10/18"}\NormalTok{,}\StringTok{"2012/10/19"}\NormalTok{,}\StringTok{"2012/10/20"}\NormalTok{,}\StringTok{"2012/10/21"}\NormalTok{,}\StringTok{"2012/10/22"}\NormalTok{,}\StringTok{"2012/10/23"}\NormalTok{,}\StringTok{"2012/10/24"}\NormalTok{,}\StringTok{"2012/10/25"}\NormalTok{,}\StringTok{"2012/10/26"}\NormalTok{,}\StringTok{"2012/10/27"}\NormalTok{,}\StringTok{"2012/10/28"}\NormalTok{,}\StringTok{"2012/10/29"}\NormalTok{,}\StringTok{"2012/10/30"}\NormalTok{,}\StringTok{"2012/10/31"}\NormalTok{,}\StringTok{"2012/11/02"}\NormalTok{,}\StringTok{"2012/1103"}\NormalTok{,}\StringTok{"2012/1105"}\NormalTok{,}\StringTok{"2012/11/06"}\NormalTok{,}\StringTok{"2012/11/07"}\NormalTok{,}\StringTok{"2012/11/08"}\NormalTok{,}\StringTok{"2012/11/11"}\NormalTok{,}\StringTok{"2012/11/12"}\NormalTok{,}\StringTok{"2012/11/13"}\NormalTok{,}\StringTok{"2012/11/15"}\NormalTok{,}\StringTok{"2012/11/16"}\NormalTok{,}\StringTok{"2012/11/17"}\NormalTok{,}\StringTok{"2012/11/18"}\NormalTok{,}\StringTok{"2012/11/19"}\NormalTok{,}\StringTok{"2012/11/20"}\NormalTok{,}\StringTok{"2012/11/21"}\NormalTok{,}\StringTok{"2012/11/22"}\NormalTok{,}\StringTok{"2012/11/23"}\NormalTok{,}\StringTok{"2012/11/24"}\NormalTok{,}\StringTok{"2012/11/25"}\NormalTok{,}\StringTok{"2012/11/26"}\NormalTok{,}\StringTok{"2012/11/27"}\NormalTok{,}\StringTok{"2012/11/28"}\NormalTok{,}\StringTok{"2012/11/29"}\NormalTok{))}
\NormalTok{dates <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{as.Date}\NormalTok{(Dates}\OperatorTok{$}\NormalTok{date, }\StringTok{"%Y/%m/%d"}\NormalTok{))}
\NormalTok{movement.sum <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(dates,step.sum) }
\KeywordTok{head}\NormalTok{(movement.sum,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  date   sum
## 2012-10-02 2012-10-02   126
## 2012-10-03 2012-10-03 11352
## 2012-10-04 2012-10-04 12116
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(movement.sum}\OperatorTok{$}\NormalTok{sum, }\DataTypeTok{xlab =} \StringTok{"Steps"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Total Steps per Day"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"dark blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Personal-Activity-Monitoring_files/figure-latex/movement.sum$sum-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{daily.mean <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(Movement}\OperatorTok{$}\NormalTok{steps,Movement}\OperatorTok{$}\NormalTok{date,mean)}
\KeywordTok{head}\NormalTok{(daily.mean,)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2012-10-02 2012-10-03 2012-10-04 2012-10-05 2012-10-06 2012-10-07 
##    0.43750   39.41667   42.06944   46.15972   53.54167   38.24653
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{step.mean <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{mean =}\NormalTok{ (daily.mean))}
\NormalTok{Dates <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{c}\NormalTok{(}\StringTok{"2012/10/02"}\NormalTok{, }\StringTok{"2012/10/03"}\NormalTok{,}\StringTok{"2012/10/04"}\NormalTok{,}\StringTok{"2012/10/05"}\NormalTok{,}\StringTok{"2012/10/06"}\NormalTok{,}\StringTok{"2012/10/07"}\NormalTok{,}\StringTok{"2012/10/09"}\NormalTok{,}\StringTok{"2012/10/10"}\NormalTok{,  }\StringTok{"2012/10/11"}\NormalTok{, }\StringTok{"2012/10/12"}\NormalTok{, }\StringTok{"2012/10/13"}\NormalTok{, }\StringTok{"2012/10/14"}\NormalTok{, }\StringTok{"2012/10/15"}\NormalTok{, }\StringTok{"2012/10/16"}\NormalTok{, }\StringTok{"2012/10/17"}\NormalTok{, }\StringTok{"2012/10/18"}\NormalTok{, }\StringTok{"2012/10/19"}\NormalTok{, }\StringTok{"2012/10/20"}\NormalTok{,}\StringTok{"2012/10/21"}\NormalTok{,}\StringTok{"2012/10/22"}\NormalTok{,}\StringTok{"2012/10/23"}\NormalTok{,}\StringTok{"2012/10/24"}\NormalTok{,}\StringTok{"2012/10/25"}\NormalTok{,}\StringTok{"2012/10/26"}\NormalTok{,}\StringTok{"2012/10/27"}\NormalTok{,}\StringTok{"2012/10/28"}\NormalTok{,}\StringTok{"2012/10/29"}\NormalTok{,}\StringTok{"2012/10/30"}\NormalTok{,}\StringTok{"2012/10/31"}\NormalTok{,}\StringTok{"2012/11/02"}\NormalTok{,}\StringTok{"2012/11/03"}\NormalTok{,}\StringTok{"2012/11/05"}\NormalTok{,}\StringTok{"2012/11/06"}\NormalTok{,}\StringTok{"2012/11/07"}\NormalTok{,}\StringTok{"2012/11/08"}\NormalTok{,}\StringTok{"2012/11/11"}\NormalTok{,}\StringTok{"2012/11/12"}\NormalTok{,}\StringTok{"2012/11/13"}\NormalTok{,}\StringTok{"2012/11/15"}\NormalTok{,}\StringTok{"2012/11/16"}\NormalTok{,}\StringTok{"2012/11/17"}\NormalTok{,}\StringTok{"2012/11/18"}\NormalTok{,}\StringTok{"2012/11/19"}\NormalTok{,}\StringTok{"2012/11/20"}\NormalTok{,}\StringTok{"2012/11/21"}\NormalTok{,}\StringTok{"2012/11/22"}\NormalTok{,}\StringTok{"2012/11/23"}\NormalTok{,}\StringTok{"2012/11/24"}\NormalTok{,}\StringTok{"2012/11/25"}\NormalTok{,}\StringTok{"2012/11/26"}\NormalTok{,}\StringTok{"2012/11/27"}\NormalTok{,}\StringTok{"2012/11/28"}\NormalTok{,}\StringTok{"2012/11/29"}\NormalTok{))}
\NormalTok{dates <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{as.Date}\NormalTok{(Dates}\OperatorTok{$}\NormalTok{date, }\StringTok{"%Y/%m/%d"}\NormalTok{))}
\NormalTok{movement.mean <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(dates,step.mean)}
\KeywordTok{head}\NormalTok{(movement.mean,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  date     mean
## 2012-10-02 2012-10-02  0.43750
## 2012-10-03 2012-10-03 39.41667
## 2012-10-04 2012-10-04 42.06944
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(movement.mean}\OperatorTok{$}\NormalTok{mean, }\DataTypeTok{xlab =} \StringTok{"Steps"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Average Steps per Day"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"dark green"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Personal-Activity-Monitoring_files/figure-latex/movement.mean$mean-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{###Step Median: }
\NormalTok{daily.median <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(Movement}\OperatorTok{$}\NormalTok{steps,Movement}\OperatorTok{$}\NormalTok{date,median)}
\KeywordTok{head}\NormalTok{(daily.median,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2012-10-02 2012-10-03 2012-10-04 
##          0          0          0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{step.median <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{median =}\NormalTok{ (daily.median))}
\NormalTok{Dates <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{c}\NormalTok{(}\StringTok{"2012/10/02"}\NormalTok{, }\StringTok{"2012/10/03"}\NormalTok{,}\StringTok{"2012/10/04"}\NormalTok{,}\StringTok{"2012/10/05"}\NormalTok{,}\StringTok{"2012/10/06"}\NormalTok{,}\StringTok{"2012/10/07"}\NormalTok{,}\StringTok{"2012/10/09"}\NormalTok{,}\StringTok{"2012/10/10"}\NormalTok{,  }\StringTok{"2012/10/11"}\NormalTok{, }\StringTok{"2012/10/12"}\NormalTok{, }\StringTok{"2012/10/13"}\NormalTok{, }\StringTok{"2012/10/14"}\NormalTok{, }\StringTok{"2012/10/15"}\NormalTok{, }\StringTok{"2012/10/16"}\NormalTok{, }\StringTok{"2012/10/17"}\NormalTok{, }\StringTok{"2012/10/18"}\NormalTok{, }\StringTok{"2012/10/19"}\NormalTok{, }\StringTok{"2012/10/20"}\NormalTok{,}\StringTok{"2012/10/21"}\NormalTok{,}\StringTok{"2012/10/22"}\NormalTok{,}\StringTok{"2012/10/23"}\NormalTok{,}\StringTok{"2012/10/24"}\NormalTok{,}\StringTok{"2012/10/25"}\NormalTok{,}\StringTok{"2012/10/26"}\NormalTok{,}\StringTok{"2012/10/27"}\NormalTok{,}\StringTok{"2012/10/28"}\NormalTok{,}\StringTok{"2012/10/29"}\NormalTok{,}\StringTok{"2012/10/30"}\NormalTok{,}\StringTok{"2012/10/31"}\NormalTok{,}\StringTok{"2012/11/02"}\NormalTok{,}\StringTok{"2012/11/03"}\NormalTok{,}\StringTok{"2012/11/05"}\NormalTok{,}\StringTok{"2012/11/06"}\NormalTok{,}\StringTok{"2012/11/07"}\NormalTok{,}\StringTok{"2012/11/08"}\NormalTok{,}\StringTok{"2012/11/11"}\NormalTok{,}\StringTok{"2012/11/12"}\NormalTok{,}\StringTok{"2012/11/13"}\NormalTok{,}\StringTok{"2012/11/15"}\NormalTok{,}\StringTok{"2012/11/16"}\NormalTok{,}\StringTok{"2012/11/17"}\NormalTok{,}\StringTok{"2012/11/18"}\NormalTok{,}\StringTok{"2012/11/19"}\NormalTok{,}\StringTok{"2012/11/20"}\NormalTok{,}\StringTok{"2012/11/21"}\NormalTok{,}\StringTok{"2012/11/22"}\NormalTok{,}\StringTok{"2012/11/23"}\NormalTok{,}\StringTok{"2012/11/24"}\NormalTok{,}\StringTok{"2012/11/25"}\NormalTok{,}\StringTok{"2012/11/26"}\NormalTok{,}\StringTok{"2012/11/27"}\NormalTok{,}\StringTok{"2012/11/28"}\NormalTok{,}\StringTok{"2012/11/29"}\NormalTok{))}
\NormalTok{dates <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{as.Date}\NormalTok{(Dates}\OperatorTok{$}\NormalTok{date, }\StringTok{"%Y/%m/%d"}\NormalTok{))}
\NormalTok{movement.median <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(dates,step.median)}
\KeywordTok{head}\NormalTok{(movement.median,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  date median
## 2012-10-02 2012-10-02      0
## 2012-10-03 2012-10-03      0
## 2012-10-04 2012-10-04      0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"/users/paulighofose/Desktop/Reproducible Research"}\NormalTok{)}
\KeywordTok{png}\NormalTok{(}\DataTypeTok{filename =} \StringTok{"Median Steps per Day.png"}\NormalTok{, }\DataTypeTok{width =} \DecValTok{480}\NormalTok{, }\DataTypeTok{height =} \DecValTok{480}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(movement.median}\OperatorTok{$}\NormalTok{median,}\DataTypeTok{col =} \StringTok{"dark red"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"Steps"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Median Steps per Day"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Yet, when considering the data along a continuum such as a time series,
the information is limited. Thus, to measure the activity (i.e.~step
count) across an acculmination of 5 minute intervals, a time series plot
was utilized.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{steps.total <-}\StringTok{ }\KeywordTok{as.table}\NormalTok{(}\KeywordTok{tapply}\NormalTok{(Movement}\OperatorTok{$}\NormalTok{steps, Movement}\OperatorTok{$}\NormalTok{interval, sum ))}
\KeywordTok{head}\NormalTok{(steps.total,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  0  5 10 
## 91 18  7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{max}\NormalTok{(steps.total)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10927
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(steps.total,}\DataTypeTok{type  =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"dark blue"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"Interval (5 Minute)"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Steps (Total)"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Steps Taken per Interval"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Personal-Activity-Monitoring_files/figure-latex/steps.total-1.pdf}

Examination of the time series indicates an increased number of steps
taken between intervals 800 and 1000, and more specifically a maximum of
10,927 steps were taken within that period.

Although simplistic in its' representation, this maximum value also
indicates an extreme within the step count observation. For if, one were
to include the complete data set, thereby replacing all ``NA'' values
with that of the population's mean, the average step count figure would
have become skewed and inconsiderable as a accurate representation of
that data. Thus, when re-examining the data and replacing those
observations with a median value of ``0.00'', the data more accurately
depicts the distribution of a complete data set.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(activity,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   steps    date interval
## 1    NA 10/1/12        0
## 2    NA 10/1/12        5
## 3    NA 10/1/12       10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(activity)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      steps            date              interval     
##  Min.   :  0.00   Length:17568       Min.   :   0.0  
##  1st Qu.:  0.00   Class :character   1st Qu.: 588.8  
##  Median :  0.00   Mode  :character   Median :1177.5  
##  Mean   : 37.38                      Mean   :1177.5  
##  3rd Qu.: 12.00                      3rd Qu.:1766.2  
##  Max.   :806.00                      Max.   :2355.0  
##  NA's   :2304
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{median <-}\StringTok{ }\DecValTok{0}
\NormalTok{activity[}\KeywordTok{is.na}\NormalTok{(activity)] =}\StringTok{ }\NormalTok{median}

\NormalTok{###Creating a new dataset of data with input values:}
\NormalTok{activity2 <-}\StringTok{ }\NormalTok{activity}
\KeywordTok{tibble}\NormalTok{(activity2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 17,568 x 3
##    steps date    interval
##    <dbl> <chr>      <int>
##  1     0 10/1/12        0
##  2     0 10/1/12        5
##  3     0 10/1/12       10
##  4     0 10/1/12       15
##  5     0 10/1/12       20
##  6     0 10/1/12       25
##  7     0 10/1/12       30
##  8     0 10/1/12       35
##  9     0 10/1/12       40
## 10     0 10/1/12       45
## # ... with 17,558 more rows
\end{verbatim}

And just as before, the new inclusive data set was looped and a total
step count per day was derived.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stepsperday <-}\StringTok{ }\KeywordTok{tapply}\NormalTok{(activity2}\OperatorTok{$}\NormalTok{steps,activity2}\OperatorTok{$}\NormalTok{date, sum)}

\NormalTok{###Renaming column:}
\NormalTok{stepsperday.with <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{steps =}\NormalTok{ (stepsperday))}
\KeywordTok{head}\NormalTok{(stepsperday.with,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          steps
## 10/1/12      0
## 10/10/12  9900
## 10/11/12 10304
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{as.array}\NormalTok{(stepsperday)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  10/1/12 10/10/12 10/11/12 10/12/12 10/13/12 10/14/12 10/15/12 10/16/12 
##        0     9900    10304    17382    12426    15098    10139    15084 
## 10/17/12 10/18/12 10/19/12  10/2/12 10/20/12 10/21/12 10/22/12 10/23/12 
##    13452    10056    11829      126    10395     8821    13460     8918 
## 10/24/12 10/25/12 10/26/12 10/27/12 10/28/12 10/29/12  10/3/12 10/30/12 
##     8355     2492     6778    10119    11458     5018    11352     9819 
## 10/31/12  10/4/12  10/5/12  10/6/12  10/7/12  10/8/12  10/9/12  11/1/12 
##    15414    12116    13294    15420    11015        0    12811        0 
## 11/10/12 11/11/12 11/12/12 11/13/12 11/14/12 11/15/12 11/16/12 11/17/12 
##        0    12608    10765     7336        0       41     5441    14339 
## 11/18/12 11/19/12  11/2/12 11/20/12 11/21/12 11/22/12 11/23/12 11/24/12 
##    15110     8841    10600     4472    12787    20427    21194    14478 
## 11/25/12 11/26/12 11/27/12 11/28/12 11/29/12  11/3/12 11/30/12  11/4/12 
##    11834    11162    13646    10183     7047    10571        0        0 
##  11/5/12  11/6/12  11/7/12  11/8/12  11/9/12 
##    10439     8334    12883     3219        0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{###Dates are copied and a new data.frame is created with Dates and steps}
\NormalTok{Dates <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{dates =} \KeywordTok{c}\NormalTok{(}\StringTok{"10/1/12"}\NormalTok{, }\StringTok{"10/10/12"}\NormalTok{, }\StringTok{"10/11/12"}\NormalTok{, }\StringTok{"10/12/12"}\NormalTok{, }\StringTok{"10/13/12"}\NormalTok{, }\StringTok{"10/14/12"}\NormalTok{, }\StringTok{"10/15/12"}\NormalTok{, }\StringTok{"10/16/12"}\NormalTok{, }\StringTok{"10/17/12"}\NormalTok{, }\StringTok{"10/18/12"}\NormalTok{, }\StringTok{"10/19/12"}\NormalTok{, }\StringTok{"10/2/12"}\NormalTok{, }\StringTok{"10/20/12"}\NormalTok{, }\StringTok{"10/21/12"}\NormalTok{, }\StringTok{"10/22/12"}\NormalTok{, }\StringTok{"10/23/12"}\NormalTok{, }\StringTok{"10/24/12"}\NormalTok{, }\StringTok{"10/25/12"}\NormalTok{, }\StringTok{"10/26/12"}\NormalTok{, }\StringTok{"10/27/12"}\NormalTok{, }\StringTok{"10/28/12"}\NormalTok{, }\StringTok{"10/29/12"}\NormalTok{,}\StringTok{"10/3/12"}\NormalTok{, }\StringTok{"10/30/12"}\NormalTok{, }\StringTok{"10/31/12"}\NormalTok{,  }\StringTok{"10/4/12"}\NormalTok{,  }\StringTok{"10/5/12"}\NormalTok{,  }\StringTok{"10/6/12"}\NormalTok{,  }\StringTok{"10/7/12"}\NormalTok{,  }\StringTok{"10/8/12"}\NormalTok{,  }\StringTok{"10/9/12"}\NormalTok{,  }\StringTok{"11/1/12"}\NormalTok{, }\StringTok{"11/10/12"}\NormalTok{, }\StringTok{"11/11/12"}\NormalTok{, }\StringTok{"11/12/12"}\NormalTok{, }\StringTok{"11/13/12"}\NormalTok{, }\StringTok{"11/14/12"}\NormalTok{, }\StringTok{"11/15/12"}\NormalTok{, }\StringTok{"11/16/12"}\NormalTok{, }\StringTok{"11/17/12"}\NormalTok{, }\StringTok{"11/18/12"}\NormalTok{, }\StringTok{"11/19/12"}\NormalTok{,  }\StringTok{"11/2/12"}\NormalTok{, }\StringTok{"11/20/12"}\NormalTok{,}\StringTok{"11/21/12"}\NormalTok{, }\StringTok{"11/22/12"}\NormalTok{, }\StringTok{"11/23/12"}\NormalTok{, }\StringTok{"11/24/12"}\NormalTok{, }\StringTok{"11/25/12"}\NormalTok{, }\StringTok{"11/26/12"}\NormalTok{, }\StringTok{"11/27/12"}\NormalTok{, }\StringTok{"11/28/12"}\NormalTok{, }\StringTok{"11/29/12"}\NormalTok{,  }\StringTok{"11/3/12"}\NormalTok{, }\StringTok{"11/30/12"}\NormalTok{, }\StringTok{"11/4/12"}\NormalTok{,  }\StringTok{"11/5/12"}\NormalTok{,  }\StringTok{"11/6/12"}\NormalTok{,  }\StringTok{"11/7/12"}\NormalTok{,  }\StringTok{"11/8/12"}\NormalTok{,  }\StringTok{"11/9/12"}\NormalTok{))}
\NormalTok{Date <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{as.Date}\NormalTok{(Dates}\OperatorTok{$}\NormalTok{dates, }\StringTok{"%m/%d/%y"}\NormalTok{))}
\KeywordTok{head}\NormalTok{(Date,}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         date
## 1 2012-10-01
## 2 2012-10-10
## 3 2012-10-11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{activity4 <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(Date,}\DataTypeTok{steps =}\NormalTok{ stepsperday.with}\OperatorTok{$}\NormalTok{steps)}
\KeywordTok{head}\NormalTok{(activity4,)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         date steps
## 1 2012-10-01     0
## 2 2012-10-10  9900
## 3 2012-10-11 10304
## 4 2012-10-12 17382
## 5 2012-10-13 12426
## 6 2012-10-14 15098
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{hist}\NormalTok{(movement.sum}\OperatorTok{$}\NormalTok{sum, }\DataTypeTok{xlab =} \StringTok{"Steps"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Total Steps per Day"}\NormalTok{, }\DataTypeTok{sub =} \StringTok{"(without NA's)"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"dark blue"}\NormalTok{)}
\KeywordTok{hist}\NormalTok{(activity4}\OperatorTok{$}\NormalTok{steps,}\DataTypeTok{xlab =} \StringTok{"Steps"}\NormalTok{,}\DataTypeTok{col =} \StringTok{"dark red"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Total Steps per Day"}\NormalTok{, }\DataTypeTok{sub =} \StringTok{"(with inputed median values)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Personal-Activity-Monitoring_files/figure-latex/unnamed-chunk-9-1.pdf}

The distribution of the data is slightly different, with the imputed
data set skewing slightly left. This indicates an increase in steps
below 15,000 in comparison to the data set without ``NA'' observations.
Thus, one must consider if the data had been complete (i.e without any
missing values) then the individual's activity monitor would have
indicated an increase in total steps per day. The only question to now
consider is whether the individuals weekday and weekend activities are
similar or not.

To do so, the character vector ``date'' was converted to a date vector
and filtered by day. Weekdays were combined to provide one collective,
as weekend observations were combined to provide another. And, just as
before the two subsets were individually looped and a mean step count
calculated.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{date.}\DecValTok{2}\NormalTok{ <-}\StringTok{ }\NormalTok{activity2}\OperatorTok{$}\NormalTok{date}
\NormalTok{date.}\DecValTok{3}\NormalTok{ <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{date =} \KeywordTok{as.Date}\NormalTok{(date.}\DecValTok{2}\NormalTok{, }\StringTok{"%m/%d/%y"}\NormalTok{))}
\NormalTok{activity.data <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(}\DataTypeTok{steps =}\NormalTok{ activity2}\OperatorTok{$}\NormalTok{steps,}\DataTypeTok{date =}\NormalTok{ date.}\DecValTok{3}\NormalTok{,}\DataTypeTok{interval =}\NormalTok{ activity2}\OperatorTok{$}\NormalTok{interval)}
\KeywordTok{head}\NormalTok{(activity.data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   steps       date interval
## 1     0 2012-10-01        0
## 2     0 2012-10-01        5
## 3     0 2012-10-01       10
## 4     0 2012-10-01       15
## 5     0 2012-10-01       20
## 6     0 2012-10-01       25
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{activity.data.}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\KeywordTok{mutate}\NormalTok{(activity.data,}\DataTypeTok{weekday =} \KeywordTok{weekdays}\NormalTok{(activity.data}\OperatorTok{$}\NormalTok{date))}
\KeywordTok{tibble}\NormalTok{(activity.data.}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 17,568 x 4
##    steps date       interval weekday
##    <dbl> <date>        <int> <chr>  
##  1     0 2012-10-01        0 Monday 
##  2     0 2012-10-01        5 Monday 
##  3     0 2012-10-01       10 Monday 
##  4     0 2012-10-01       15 Monday 
##  5     0 2012-10-01       20 Monday 
##  6     0 2012-10-01       25 Monday 
##  7     0 2012-10-01       30 Monday 
##  8     0 2012-10-01       35 Monday 
##  9     0 2012-10-01       40 Monday 
## 10     0 2012-10-01       45 Monday 
## # ... with 17,558 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{###Sorting Days:}
\NormalTok{activity6m <-}\StringTok{ }\NormalTok{activity.data.}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(weekday }\OperatorTok{==}\StringTok{ "Monday"}\NormalTok{)}
\NormalTok{activity6t <-}\StringTok{ }\NormalTok{activity.data.}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(weekday }\OperatorTok{==}\StringTok{ "Tuesday"}\NormalTok{)}
\NormalTok{activity6w <-}\StringTok{ }\NormalTok{activity.data.}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(weekday }\OperatorTok{==}\StringTok{ "Wednesday"}\NormalTok{)}
\NormalTok{activity6th <-}\StringTok{ }\NormalTok{activity.data.}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(weekday }\OperatorTok{==}\StringTok{ "Thursday"}\NormalTok{)}
\NormalTok{activity6f <-}\StringTok{ }\NormalTok{activity.data.}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(weekday }\OperatorTok{==}\StringTok{ "Friday"}\NormalTok{)}
\NormalTok{activity6sat <-}\StringTok{ }\NormalTok{activity.data.}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(weekday }\OperatorTok{==}\StringTok{ "Saturday"}\NormalTok{)}
\NormalTok{activity6sun <-}\StringTok{ }\NormalTok{activity.data.}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(weekday }\OperatorTok{==}\StringTok{ "Sunday"}\NormalTok{)}

\NormalTok{###Combining weekdays and weekend days:}
\NormalTok{weekday <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(activity6m, activity6t, activity6w, activity6th, activity6f)}
\NormalTok{weekend <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(activity6sat, activity6sun)}


\NormalTok{###Creating time series of weekday and weekend activity:}
\NormalTok{steps.weekday <-}\StringTok{ }\KeywordTok{as.table}\NormalTok{(}\KeywordTok{tapply}\NormalTok{(weekday}\OperatorTok{$}\NormalTok{steps, weekday}\OperatorTok{$}\NormalTok{interval, mean ))}
\NormalTok{steps.weekend <-}\StringTok{ }\KeywordTok{as.table}\NormalTok{(}\KeywordTok{tapply}\NormalTok{(weekend}\OperatorTok{$}\NormalTok{steps, weekend}\OperatorTok{$}\NormalTok{interval,mean ))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(steps.weekday,}\DataTypeTok{type  =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"dark blue"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"Interval (5 Minute)"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Steps (Total)"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Average Weekday Steps"}\NormalTok{)}
\KeywordTok{plot}\NormalTok{(steps.weekend,}\DataTypeTok{type  =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \StringTok{"dark red"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"Interval (5 Minute)"}\NormalTok{, }\DataTypeTok{ylab =} \StringTok{"Steps (Total)"}\NormalTok{, }\DataTypeTok{main =} \StringTok{"Average Weekend Steps"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Personal-Activity-Monitoring_files/figure-latex/steps.weekday-1.pdf}

In comparison the average weekday step count appears greater, however if
one were to remove the weekday maximum, one would notice that the
weekend step count maximum and occurrence are greater and more frequent.
Indicating greater mobility within that time period.

\end{document}
